[WIP] Minimal implementation without numba_scipy
Blue-Yonder-OSS/cyclic-boosting pull request #27
Opened 2023-04-22 14:01 UTC by StefanUlbrich

Use naïve implementation of `gammaln` for positive integers instead of `scipy.special.gammaln`

2023-04-22 14:10 UTC, StefanUlbrich commented
Test passed successfully. @FelixWick I assume that means the workaround is functional? 
Shall we include [benchmark in our tests](https://pytest-benchmark.readthedocs.io/en/stable/) to catch performance regressions in the future?

2023-04-22 14:51 UTC, StefanUlbrich commented
Included an error in the function and the other tests passed. Can we adjust testing for that?

2023-04-22 19:30 UTC, FelixWick commented
It would be great to include performance tests, yes.

I would have expected the integration test for the width model to fail if you include an error in gammaln.
Also, it should at least give a different result if you require an integer input in your implementation.

2023-04-23 09:12 UTC, FelixWick commented
That looks promising. Please go ahead with an implementation of your proposed function in the package. If you could add a performance check on the integration test of the width mode, along with some variations to make sure we get compatible results, that would be awesome.

2023-04-26 05:39 UTC, FelixWick commented
Is this pull request ready for review and merge?

2023-05-19 11:55 UTC, FelixWick commented on tests/test_gammaln.py
> +
What about the range between 2 and 10?

2023-05-19 11:57 UTC, FelixWick commented on examples/gammaln_test.ipynb
Can you plot for higher values, too?

2023-05-19 12:03 UTC, FelixWick commented
I have checked the resulting values for c compared to master (using numba_scipy) and there are quite some deviations (mean of c in integration test increases from 0.365 to 0.391). Can we make numba_scipy an optional dependency for the ones who need a (potentially) more accurate width model and otherwise use the (potentially) less accurate implementation in this pull request?

2023-05-19 12:05 UTC, FelixWick requested changes
- please check comparison for higher values
- please make use of numba_scipy optional

2023-08-16 07:32 UTC, FelixWick commented
@StefanUlbrich any progress on this?

2023-08-16 19:04 UTC, StefanUlbrich commented
Apologies, still on it and will continue over the weekend—I also found a better pure python version that I want to try out.

2023-08-20 15:47 UTC, StefanUlbrich commented
I have not been able to figure out how to specify `scipy-numba` as an optional / package extra. 
Poetry has problems ignoring the dependency for python 3.10+ ... Yet the code checks whether it is installed, so we could have the users take care of this by manually installing it.

The fast and accurate implementation I mentioned is [here](https://stackoverflow.com/a/54851190) and looks simple enough to implement. @FelixWick what do you recommend? The implementation looks accurate enough and straight forward

2023-08-21 06:12 UTC, FelixWick commented
So, you're saying you want to replace your current algorithm with that one? I'm ok with that, of course, as long as it's faster and more accurate.

2023-08-21 07:00 UTC, StefanUlbrich commented
> So, you're saying you want to replace your current algorithm with that one? I'm ok with that, of course, as long as it's faster and more accurate.

How did you test both? Do you have code suitable for a unit test? It will not be faster as the one in scipy—that is highly optimized after all—but it is better than sticking with the old numba-scipy.

2023-08-21 07:15 UTC, FelixWick commented
Ok, maybe this is a misunderstanding :). I thought you're suggesting yet another implementation (from your stackoverflow link). So, that one is the same you already implemented before?

2023-08-21 07:57 UTC, StefanUlbrich commented
> Ok, maybe this is a misunderstanding :). I thought you're suggesting yet another implementation (from your stackoverflow link). So, that one is the same you already implemented before?

It is a different one (it's iterative) but seems to be on par in terms of accuracy and close to performance with scipy from what I read

2023-08-21 08:05 UTC, FelixWick commented
Ok, that's what I understood, good. No, I don't have a dedicated test. I think your checks in the notebook are just fine. Additionally, I used an integration test to check the consequences for the negative binomial overdispersion parameter in the end. These were quite large for your current implementation. Would be interesting to compare with the new one.

2023-09-16 13:21 UTC, FelixWick commented
I think I found a much simpler solution :), see https://github.com/Blue-Yonder-OSS/cyclic-boosting/pull/43.

2023-09-16 13:21 UTC, closed without merging